// src/proto/pb_wrapper.c
#include "proto/pb_wrapper.h"
#include "pb_encode.h" // NanoPB library

size_t proto_serialize(const Packet* packet, uint8_t* buffer, size_t buffer_size) {
    // Create an output stream writing to our buffer
    pb_ostream_t stream = pb_ostream_from_buffer(buffer, buffer_size);

    // Encode
    // Note: 'Packet_fields' is generated by NanoPB
    // We assume the generated code provides this descriptor
    if (!pb_encode(&stream, Packet_fields, packet)) {
        // Encoding failed
        return 0;
    }

    // Return number of bytes written
    return stream.bytes_written;
}