/**
 * @file telemetry_mock.c
 * @brief Mocks the code normally generated by NanoPB.
 * Use this to compile without installing the protobuf python compiler.
 */

#include "proto/pb.h"

// Define the struct layout for NanoPB
// These must match the typedefs in your mock header

// Mock Field Descriptors (Empty for now, just to satisfy Linker)
// In a real build, these contain the binary schema.
const pb_msgdesc_t* Packet_fields = NULL;