/**
 * @file tokenizer.h
 * @brief Vocabulary-based Text Encoder.
 * 
 * Loads a vocabulary file generated by the Python training lab
 * and maps raw log words to integer indices for the AI model.
 */

#ifndef BLACKBOX_PARSER_TOKENIZER_H
#define BLACKBOX_PARSER_TOKENIZER_H

#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>
#include <array>

namespace blackbox::parser {

    class Tokenizer {
    public:
        Tokenizer();
        ~Tokenizer() = default;

        /**
         * @brief Load vocabulary from disk.
         * 
         * Format expected: One word per line.
         * Line 0 = Index 0
         * Line 1 = Index 1
         * ...
         * 
         * @param path Path to vocab.txt
         * @return true if loaded successfully
         */
        bool load_vocabulary(const std::string& path);

        /**
         * @brief Converts a log message into a fixed-size vector.
         * 
         * Uses "Bag of Words" or "Sequence" encoding.
         * 
         * @param text The raw message (e.g., "Failed password for root")
         * @param out_vector Reference to the output array (e.g., 128 floats)
         */
        void encode(std::string_view text, std::array<float, 128>& out_vector);

    private:
        // O(1) Lookup table: Word -> Index
        std::unordered_map<std::string, int> vocab_map_;
        
        // Special token IDs
        int unk_token_id_ = 0; // [UNK] Unknown word
        int pad_token_id_ = 1; // [PAD] Padding
    };

} // namespace blackbox::parser

#endif // BLACKBOX_PARSER_TOKENIZER_H